version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: phatgpt-next-web:dev
    stdin_open: true
    tty: true
    environment:
      PROXY_URL: ""
      OPENAI_API_KEY: ""
      CODE: ""
    ports:
      - "3000:3000"
    volumes:
      - .:/app